<?php

/**
 * Mock provider used for testing the whole pipeline without API keys.
 *
 * Implements text, audio and video capabilities.
 *
 * @package KritiAI
 */

namespace KritiAI\Providers;

use KritiAI\Core\Provider;
use KritiAI\Core\Text_Provider;
use KritiAI\Core\Image_Provider;
use KritiAI\Core\Audio_Provider;
use KritiAI\Core\Video_Provider;

/**
 * Class Mock_Provider
 */
class Mock_Provider extends Provider implements Text_Provider, Image_Provider, Audio_Provider, Video_Provider
{



	/**
	 * Generate a fake article as JSON so the split logic is exercised.
	 *
	 * @param string $prompt The prompt.
	 * @param array  $params Parameters.
	 * @return array
	 */
	public function generate_text($prompt, $params)
	{
		$topic = trim(wp_strip_all_tags($prompt));
		$topic = $topic ? $topic : __('artificial intelligence', 'kriti-ai');

		/* translators: %s: Topic name. */
		$title   = sprintf(__('A Practical Introduction to %s', 'kriti-ai'), ucwords($topic));
		$content = sprintf(
			/* translators: %1$s: Topic name inserted in paragraph text. */
			__(
				'<p>This is a demonstration article generated by Kriti AI\'s mock provider. It stands in for a real language model so you can validate the plugin workflow without an API key.</p><p>Modern teams use %1$s to automate research, drafting and production pipelines. Start small, measure results, and iterate. This paragraph exists so the generated content has enough length to look realistic in the editor and on the dashboard.</p><h2>Why it matters</h2><p>Draft-first workflows let you review everything an AI produces before it becomes visible to your audience.</p>',
				'kriti-ai'
			),
			$topic
		);

		$payload = wp_json_encode(
			array(
				'title'   => $title,
				'content' => $content,
			)
		);

		return array(
			'content'    => $payload,
			'tokens_in'  => 12,
			'tokens_out' => 64,
			'model'      => $this->get_model($params),
		);
	}

	/**
	 * Generate a 1x1 mock PNG image file.
	 *
	 * @param string $prompt Description of image.
	 * @param array  $params Parameters.
	 * @return array|\WP_Error
	 */
	public function generate_image($prompt, $params)
	{
		// 1x1 transparent PNG binary fixture.
		$png = base64_decode( // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_decode -- Decoding 1x1 PNG fixture.
			'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=',
			true
		);

		$file = $this->write_tmp_file($png, 'png');

		if (is_wp_error($file)) {
			return $file;
		}

		return array(
			'tmp_path'  => $file,
			'mime'      => 'image/png',
			'extension' => 'png',
		);
	}

	/**
	 * Generate a short sine-wave WAV file.
	 *
	 * @param string $text Text to "speak".
	 * @param array  $params Parameters.
	 * @return array
	 */
	public function synthesize_audio($text, $params)
	{
		$duration         = 1.0;
		$sample_rate      = 8000;
		$channels         = 1;
		$bits             = 16;
		$bytes_per_sample = $channels * $bits / 8;
		$data_size        = (int) ($sample_rate * $duration) * $bytes_per_sample;

		$header  = 'RIFF' . pack('V', 36 + $data_size) . 'WAVE';
		$header .= 'fmt ' . pack('VvvVVvv', 16, 1, $channels, $sample_rate, $sample_rate * $bytes_per_sample, $bytes_per_sample, $bits);
		$header .= 'data' . pack('V', $data_size);

		$body = '';
		for ($i = 0; $i < $sample_rate * $duration; $i++) {
			$t        = $i / $sample_rate;
			$envelope = 1 - ($i / ($sample_rate * $duration));
			$sample   = (int) (32767 * 0.5 * $envelope * sin(2 * M_PI * 440 * $t));
			$body    .= pack('v', $sample);
		}

		$file = $this->write_tmp_file($header . $body, 'wav');

		if (is_wp_error($file)) {
			return $file;
		}

		return array(
			'tmp_path'  => $file,
			'mime'      => 'audio/wav',
			'extension' => 'wav',
		);
	}

	/**
	 * Start video generation. Mock is synchronous.
	 *
	 * @param string $prompt Video description.
	 * @param array  $params Parameters.
	 * @return array
	 */
	public function start_video($prompt, $params)
	{
		return $this->build_video_file();
	}

	/**
	 * Mock has no async polling; return a completed file.
	 *
	 * @param string $external_id Provider-side job id.
	 * @param array  $params Parameters.
	 * @return array
	 */
	public function poll_video($external_id, $params)
	{
		return $this->build_video_file();
	}

	/**
	 * Build a tiny valid GIF used as a video stand-in.
	 *
	 * @return array|WP_Error
	 */
	private function build_video_file()
	{
		// 1x1 GIF89a, single transparent frame.
		$gif = base64_decode( // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_decode -- Decoding constant 1x1 GIF fixture.
			'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
			true
		);

		$file = $this->write_tmp_file($gif, 'gif');

		if (is_wp_error($file)) {
			return $file;
		}

		return array(
			'status'    => 'completed',
			'tmp_path'  => $file,
			'mime'      => 'image/gif',
			'extension' => 'gif',
		);
	}
}
